In [1]:
# Pandas for data analysis
import pandas as pd

# Numpy for mathematical operations
import numpy as np

# matplotlib and seaborn for visualization
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# Reading dataset
df = pd.read_csv('Salary_Data.csv')

In [3]:
df.head()

  Age Group  Age  Income
0     Youth   19   22000
1     Youth   19   22500
2     Youth   19   23000
3     Youth   21   24000
4     Youth   21   24500

In [4]:
# Check for inconsistencies
df.isnull().sum()

Age Group    0
Age          0
Income       0
dtype: int64

In [5]:
# Check datatype
df.dtypes

Age Group    object
Age           int64
Income        int64
dtype: object

In [6]:
# mean income grouped by age
income_gb_age_mean = df.groupby('Age')['Income'].mean()
income_gb_age_mean

Age
19     22500.0
21     24500.0
23     26500.0
24     28500.0
25     30500.0
26     35500.0
28     38500.0
30     42500.0
32     45500.0
35     48500.0
36     52500.0
38     55500.0
40     58500.0
42     61500.0
45     65500.0
46     68500.0
48     72500.0
50     76500.0
52     80500.0
55     85500.0
56     88500.0
58     92500.0
60     96500.0
62    100500.0
65    105500.0
66     89500.0
68     87500.0
70     85500.0
72     83500.0
75     81500.0
Name: Income, dtype: float64

In [7]:
# median of income grouped by age
income_gb_age_median = df.groupby('Age')['Income'].median()
income_gb_age_median

Age
19     22500.0
21     24500.0
23     26500.0
24     28500.0
25     30500.0
26     35500.0
28     38500.0
30     42500.0
32     45500.0
35     48500.0
36     52500.0
38     55500.0
40     58500.0
42     61500.0
45     65500.0
46     68500.0
48     72500.0
50     76500.0
52     80500.0
55     85500.0
56     88500.0
58     92500.0
60     96500.0
62    100500.0
65    105500.0
66     89500.0
68     87500.0
70     85500.0
72     83500.0
75     81500.0
Name: Income, dtype: float64

In [8]:
# Standard deviation of income grouped by age
income_gb_age_std = df.groupby('Age')['Income'].std()
income_gb_age_std

Age
19    500.0
21    500.0
23    500.0
24    500.0
25    500.0
26    500.0
28    500.0
30    500.0
32    500.0
35    500.0
36    500.0
38    500.0
40    500.0
42    500.0
45    500.0
46    500.0
48    500.0
50    500.0
52    500.0
55    500.0
56    500.0
58    500.0
60    500.0
62    500.0
65    500.0
66    500.0
68    500.0
70    500.0
72    500.0
75    500.0
Name: Income, dtype: float64

In [9]:
# mean income grouped by Age Group
income_gb_age_mean = df.groupby('Age Group')['Income'].mean()
income_gb_age_mean

Age Group
Adult           58700.0
Middle Aged     76700.0
Retired         85500.0
Senior Adult    96700.0
Young Adult     42100.0
Youth           26500.0
Name: Income, dtype: float64

In [10]:
# median of income grouped by age group
income_gb_age_mean = df.groupby('Age Group')['Income'].median()
income_gb_age_mean

Age Group
Adult           58500.0
Middle Aged     76500.0
Retired         85500.0
Senior Adult    96500.0
Young Adult     42500.0
Youth           26500.0
Name: Income, dtype: float64

In [11]:
# Standard deviation income grouped by Age Group
income_gb_age_mean = df.groupby('Age Group')['Income'].mean()
income_gb_age_mean

Age Group
Adult           58700.0
Middle Aged     76700.0
Retired         85500.0
Senior Adult    96700.0
Young Adult     42100.0
Youth           26500.0
Name: Income, dtype: float64

In [12]:
# Describe all statistics
data_desc_gb_age = pd.DataFrame(df.groupby('Age').describe())
data_desc_gb_age

    Income
     count      mean    std       min       25%       50%       75%       max
Age
19     3.0   22500.0  500.0   22000.0   22250.0   22500.0   22750.0   23000.0
21     3.0   24500.0  500.0   24000.0   24250.0   24500.0   24750.0   25000.0
23     3.0   26500.0  500.0   26000.0   26250.0   26500.0   26750.0   27000.0
24     3.0   28500.0  500.0   28000.0   28250.0   28500.0   28750.0   29000.0
25     3.0   30500.0  500.0   30000.0   30250.0   30500.0   30750.0   31000.0
26     3.0   35500.0  500.0   35000.0   35250.0   35500.0   35750.0   36000.0
28     3.0   38500.0  500.0   38000.0   38250.0   38500.0   38750.0   39000.0
30     3.0   42500.0  500.0   42000.0   42250.0   42500.0   42750.0   43000.0
32     3.0   45500.0  500.0   45000.0   45250.0   45500.0   45750.0   46000.0
35     3.0   48500.0  500.0   48000.0   48250.0   48500.0   48750.0   49000.0
36     3.0   52500.0  500.0   52000.0   52250.0   52500.0   52750.0   53000.0
38     3.0   55500.0  500.0   55000.0   55250.0   55500.0   55750.0   56000.0
40     3.0   58500.0  500.0   58000.0   58250.0   58500.0   58750.0   59000.0
42     3.0   61500.0  500.0   61000.0   61250.0   61500.0   61750.0   62000.0
45     3.0   65500.0  500.0   65000.0   65250.0   65500.0   65750.0   66000.0
46     3.0   68500.0  500.0   68000.0   68250.0   68500.0   68750.0   69000.0
48     3.0   72500.0  500.0   72000.0   72250.0   72500.0   72750.0   73000.0
50     3.0   76500.0  500.0   76000.0   76250.0   76500.0   76750.0   77000.0
52     3.0   80500.0  500.0   80000.0   80250.0   80500.0   80750.0   81000.0
55     3.0   85500.0  500.0   85000.0   85250.0   85500.0   85750.0   86000.0
56     3.0   88500.0  500.0   88000.0   88250.0   88500.0   88750.0   89000.0
58     3.0   92500.0  500.0   92000.0   92250.0   92500.0   92750.0   93000.0
60     3.0   96500.0  500.0   96000.0   96250.0   96500.0   96750.0   97000.0
62     3.0  100500.0  500.0  100000.0  100250.0  100500.0  100750.0  101000.0
65     3.0  105500.0  500.0  105000.0  105250.0  105500.0  105750.0  106000.0
66     3.0   89500.0  500.0   89000.0   89250.0   89500.0   89750.0   90000.0
68     3.0   87500.0  500.0   87000.0   87250.0   87500.0   87750.0   88000.0
70     3.0   85500.0  500.0   85000.0   85250.0   85500.0   85750.0   86000.0
72     3.0   83500.0  500.0   83000.0   83250.0   83500.0   83750.0   84000.0
75     3.0   81500.0  500.0   81000.0   81250.0   81500.0   81750.0   82000.0

In [13]:
# Describe all statistics
data_desc_gb_age_group = pd.DataFrame(df.groupby('Age Group').describe())
data_desc_gb_age_group

               Age                                               Income  \
             count  mean       std   min   25%   50%   75%   max  count
Age Group
Adult         15.0  40.2  3.233751  36.0  38.0  40.0  42.0  45.0   15.0
Middle Aged   15.0  50.2  3.233751  46.0  48.0  50.0  52.0  55.0   15.0
Retired       15.0  70.2  3.233751  66.0  68.0  70.0  72.0  75.0   15.0
Senior Adult  15.0  60.2  3.233751  56.0  58.0  60.0  62.0  65.0   15.0
Young Adult   15.0  30.2  3.233751  26.0  28.0  30.0  32.0  35.0   15.0
Youth         15.0  22.4  2.229670  19.0  21.0  23.0  24.0  25.0   15.0

                                                                         \
                 mean          std      min      25%      50%       75%
Age Group
Adult         58700.0  4712.445528  52000.0  55250.0  58500.0   61750.0
Middle Aged   76700.0  6169.626060  68000.0  72250.0  76500.0   80750.0
Retired       85500.0  2958.039892  81000.0  83250.0  85500.0   87750.0
Senior Adult  96700.0  6169.626060  88000.0  92250.0  96500.0  100750.0
Young Adult   42100.0  4855.777119  35000.0  38250.0  42500.0   45750.0
Youth         26500.0  2958.039892  22000.0  24250.0  26500.0   28750.0


                   max
Age Group
Adult          66000.0
Middle Aged    86000.0
Retired        90000.0
Senior Adult  106000.0
Young Adult    49000.0
Youth          31000.0

In [14]:
df = pd.read_csv('iris.csv')
df = df.drop('Id', axis=1)

In [15]:
cols = list(df.columns)
cols.remove('Species')

for col in cols:
    mean = df.groupby('Species')[col].mean()
    print(f"Mean for {col}:")
    print(mean)
    print()

    std = df.groupby('Species')[col].std()
    print(f"Std dev for {col}:")
    print(std)
    print()

    qtl_25 = df.groupby('Species')[col].quantile(0.25)
    print(f"25% for {col}:")
    print(qtl_25)
    print()

Mean for SepalLengthCm:
Species
Iris-setosa        5.006
Iris-versicolor    5.936
Iris-virginica     6.588
Name: SepalLengthCm, dtype: float64

Std dev for SepalLengthCm:
Species
Iris-setosa        0.352490
Iris-versicolor    0.516171
Iris-virginica     0.635880
Name: SepalLengthCm, dtype: float64

25% for SepalLengthCm:
Species
Iris-setosa        4.800
Iris-versicolor    5.600
Iris-virginica     6.225
Name: SepalLengthCm, dtype: float64

Mean for SepalWidthCm:
Species
Iris-setosa        3.418
Iris-versicolor    2.770
Iris-virginica     2.974
Name: SepalWidthCm, dtype: float64

Std dev for SepalWidthCm:
Species
Iris-setosa        0.381024
Iris-versicolor    0.313798
Iris-virginica     0.322497
Name: SepalWidthCm, dtype: float64

25% for SepalWidthCm:
Species
Iris-setosa        3.125
Iris-versicolor    2.525
Iris-virginica     2.800
Name: SepalWidthCm, dtype: float64

Mean for PetalLengthCm:
Species
Iris-setosa        1.464
Iris-versicolor    4.260
Iris-virginica     5.552
Name: PetalLengthCm, dtype: float64

Std dev for PetalLengthCm:
Species
Iris-setosa        0.173511
Iris-versicolor    0.469911
Iris-virginica     0.551895
Name: PetalLengthCm, dtype: float64

25% for PetalLengthCm:
Species
Iris-setosa        1.4
Iris-versicolor    4.0
Iris-virginica     5.1
Name: PetalLengthCm, dtype: float64

Mean for PetalWidthCm:
Species
Iris-setosa        0.244
Iris-versicolor    1.326
Iris-virginica     2.026
Name: PetalWidthCm, dtype: float64

Std dev for PetalWidthCm:
Species
Iris-setosa        0.107210
Iris-versicolor    0.197753
Iris-virginica     0.274650
Name: PetalWidthCm, dtype: float64

25% for PetalWidthCm:
Species
Iris-setosa        0.2
Iris-versicolor    1.2
Iris-virginica     1.8
Name: PetalWidthCm, dtype: float64